### ISSUE TITLE
find out how to run rspec in a wagon

### ISSUE THREAD

**Issue by hairmare** [pfadipatria/hitobito_patria#2]

**Comment by hairmare** [comment]
hmmmm....

**Comment by hairmare** [comment]
This should now work by running `rake wagon:test WAGON=patria` in the hitobito clone or rake locally.

Some issues i found (that needed fixing):
- erroneous schema data in `pfadipatria/hitobito/db/schema.rb` makes wagon migrations fail
- `spec/models/corps_spec.rb` should test `Group::Corps` and not `Corps`

I also added an example in `spec/` to get everyone up and running a bit faster.

**Comment by PlekszyGladz** [comment]
`rake wagon:test WAGON=patria` does not complete on my system (`Errno::EACCES: Permission denied - .../hitobito/db/test.sqlite3`)
could be a problem with windows, but i have not found anything usefull yet...

**Comment by hairmare** [comment]
If you are running a rails server at the same time? There might be a lock on the file.

Does it work when you run `rake` in the wagon itself?

**Comment by PlekszyGladz** [comment]
Raking in the wagon did not really work but i tried out this fix: https://github.com/mvz/memory_test_fix/
That solved the the problem with the permission but its still not completing (An error occurs when the migrations are executed)

**Comment by hairmare** [comment]
Did you pull all my changes? Please post the error and its trace if that does not help.

The memory_test_fix doesn't solve the underlying problem, but thats OK if it works for now. Please don't check in your changes related to that.

**Comment by PlekszyGladz** [comment]
All repos are up to date but the error still persits. Heres the error and its trace:

```
** Invoke app:db:load_config (first_time)
** Execute app:db:load_config
** Execute app:db:test:prepare
** Invoke app:db:test:load (first_time)
** Invoke app:db:test:purge (first_time)
** Invoke app:environment
** Invoke app:db:load_config
** Execute app:db:test:purge
** Execute app:db:test:load
** Invoke app:db:test:load_schema (first_time)
** Invoke app:db:test:purge
** Execute app:db:test:load_schema
** Invoke app:db:schema:load (first_time)
** Invoke app:environment
** Invoke app:db:load_config
** Execute app:db:schema:load
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: people: ALTER TABLE "people" ADD "salutation" varchar(255)C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/sqlite3-1.3.9-x86-mingw32/lib/sqlite3/database.rb:91:in `initialize'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/sqlite3-1.3.9-x86-mingw32/lib/sqlite3/database.rb:91:in `new'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/sqlite3-1.3.9-x86-mingw32/lib/sqlite3/database.rb:91:in `prepare'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/sqlite3-1.3.9-x86-mingw32/lib/sqlite3/database.rb:134:in `execute'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:331:in `block in execute'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:331:in `execute'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:360:in `add_column'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:454:in `add_column'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/schema_plus-1.4.0/lib/schema_plus/active_record/foreign_keys.rb:124:in `add_column'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:629:in `block in method_missing'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:601:in `block in say_with_time'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:601:in `say_with_time'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:621:in `method_missing'
C:/Users/Nicolas Kessler/Documents/Uni/PSE/Hitobito/hitobito_pbs/db/migrate/20131211121712_add_pfadi_attributes.rb:10:in `change'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:575:in `exec_migration'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:559:in `block (2 levels) in migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:558:in `block in migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:557:in `migrate'
C:in `migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:963:in `block in execute_migration_in_transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:1009:in `block in ddl_transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:221:in `within_new_transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/transactions.rb:209:in `transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:1009:in `ddl_transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:962:in `execute_migration_in_transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:924:in `block in migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:920:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:920:in `migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:768:in `up'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-4.0.4/lib/active_record/migration.rb:746:in `migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/wagons-0.2.2/lib/wagons/wagon.rb:63:in `migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/wagons-0.2.2/lib/wagons/wagon_tasks.rake:134:in `block (5 levels) in <top (required)>'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/wagons-0.2.2/lib/wagons/wagon_tasks.rake:134:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/wagons-0.2.2/lib/wagons/wagon_tasks.rake:134:in `block (4 levels) in <top (required)>'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:240:in `call'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:240:in `block in execute'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:235:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:235:in `execute'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:199:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:199:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:199:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:199:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/task.rb:165:in `invoke'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:150:in `invoke_task'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:106:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:106:in `block in top_level'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:115:in `run_with_threads'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:100:in `top_level'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:78:in `block in run'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:173:in `standard_exception_handling'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/lib/rake/application.rb:75:in `run'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.2.1/bin/rake:33:in `<top (required)>'
C:/RailsInstaller/Ruby1.9.3/bin/rake:23:in `load'
C:/RailsInstaller/Ruby1.9.3/bin/rake:23:in `<main>'
Tasks: TOP => default => spec => test:prepare => db:test:prepare => app:db:test:prepare
rake aborted!
Command failed with status (1): [cd C:/Users/Nicolas Kessler/Documents/Uni/...]
```

**Comment by hairmare** [comment]
Normally this error happens when `hitobito/db/schema.rb` contains fields that should be in a wagon. Could you make sure the file has no local edits and check for similar files in the wagons. Wagons should not have a `schema.rb` as far as i can tell.

You need to clean the file after running `rake db:schema:dump`. I usually check its contents for things that should go into the engine with `git diff db/schema.rb` and then revert changes belonging to a wagon with `git checkout db/schema.rb`

**Comment by PlekszyGladz** [comment]
I double checked the `schema.rb` of hitobito and there are no fields from any wagons. Also there are no schemas inside the wagons but ther error still persits... It definitely seems to be a problem with windows because it seems to work on ubuntu. 
If the problem is not solvable in any reasonable time I will try to write the test in the core wagon (where they are executable) and then transfer them to the patria wagon for the commit.
